# Generated by Django 5.2.10 on 2026-02-28 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0005_charge_template_versioning_and_billline_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(help_text='Display identifier like P1, B-12, Slot-45', max_length=50)),
                ('slot_type', models.CharField(choices=[('OPEN', 'Open'), ('COVERED', 'Covered'), ('BASEMENT', 'Basement'), ('VISITOR', 'Visitor'), ('SOLD', 'Sold')], default='OPEN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_rotational', models.BooleanField(default=False)),
                ('is_transferable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_slots', to='housing.society')),
            ],
            options={
                'ordering': ('slot_number',),
                'unique_together': {('society', 'slot_number')},
            },
        ),
    ]
