# Generated by Django 5.2.10 on 2026-02-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_charge_template_versioning_and_billline_snapshots'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(help_text='Vehicle registration number', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car (4 Wheeler)'), ('BIKE', 'Bike (2 Wheeler)'), ('OTHER', 'Other')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, help_text='Optional: Who primarily uses this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='housing.member')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='housing.society')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='housing.unit')),
            ],
            options={
                'ordering': ('vehicle_number',),
                'unique_together': {('society', 'vehicle_number')},
            },
        ),
    ]
