# Generated by Django 5.2.10 on 2026-02-28 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_charge_template_versioning_and_billline_snapshots'),
        ('parking', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingVehicleLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(choices=[('OWNER', 'Owner'), ('TENANT', 'Tenant')], max_length=20)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car (4 Wheeler)'), ('BIKE', 'Bike (2 Wheeler)'), ('OTHER', 'Other')], max_length=20)),
                ('max_allowed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_vehicle_limits', to='housing.society')),
            ],
            options={
                'ordering': ('society', 'member_role', 'vehicle_type'),
                'unique_together': {('society', 'member_role', 'vehicle_type')},
            },
        ),
    ]
