# Generated by Django 5.2.10 on 2026-03-07 08:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_charge_template_versioning_and_billline_snapshots'),
        ('parking', '0006_vehicle_rule_status_safety_states'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='owned_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_parking_slots', to='housing.unit'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='parking_model',
            field=models.CharField(choices=[('COMMON', 'Common'), ('ASSIGNED', 'Assigned'), ('SOLD', 'Sold')], default='COMMON', max_length=20),
        ),
        migrations.CreateModel(
            name='ParkingSlotOwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='parking.parkingslot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_slot_ownership_history', to='housing.unit')),
            ],
            options={
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ParkingPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('SOLD', 'Sold')], default='SOLD', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STANDBY', 'Standby'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_parking_permits', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_permits', to='parking.parkingslot')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_permits', to='housing.society')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_permits', to='housing.unit')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_permits', to='parking.vehicle')),
            ],
            options={
                'ordering': ('-issued_at', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('slot',), name='uniq_active_parking_permit_per_slot')],
            },
        ),
    ]
