# Generated by Django 5.2.10 on 2026-03-11 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_charge_template_versioning_and_billline_snapshots'),
        ('parking', '0007_parkingslot_owned_unit_parkingslot_parking_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingpermit',
            name='permit_type',
            field=models.CharField(choices=[('SOLD', 'Sold'), ('OPEN', 'Open'), ('ROTATIONAL', 'Rotational')], default='SOLD', max_length=20),
        ),
        migrations.CreateModel(
            name='ParkingRotationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(default='Default Rotational Policy', max_length=255)),
                ('rotation_period_months', models.PositiveIntegerField(default=1)),
                ('rotation_method', models.CharField(choices=[('QUEUE', 'Queue'), ('LOTTERY', 'Lottery')], default='QUEUE', max_length=20)),
                ('vehicle_required_before_apply', models.BooleanField(default=True)),
                ('allow_sold_parking_owner', models.BooleanField(default=True)),
                ('allow_tenant_application', models.BooleanField(default=True)),
                ('max_rotational_slots_per_unit', models.PositiveIntegerField(default=1)),
                ('max_total_parking_per_unit', models.PositiveIntegerField(default=1)),
                ('skip_units_with_outstanding_dues', models.BooleanField(default=False)),
                ('skip_units_with_parking_violation', models.BooleanField(default=False)),
                ('unused_parking_reassignment_days', models.PositiveIntegerField(default=0)),
                ('application_window_days', models.PositiveIntegerField(default=7)),
                ('priority_rule', models.CharField(choices=[('NO_PARKING_FIRST', 'No Parking First'), ('QUEUE_ORDER', 'Queue Order'), ('LOTTERY_ONLY', 'Lottery Only')], default='QUEUE_ORDER', max_length=30)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parking_rotation_policies', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_rotation_policies', to='housing.society')),
            ],
            options={
                'ordering': ('society', '-effective_from', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ParkingRotationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField()),
                ('cycle_start_date', models.DateField()),
                ('cycle_end_date', models.DateField()),
                ('total_rotational_spots', models.PositiveIntegerField(default=0)),
                ('allocation_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ALLOCATED', 'Allocated'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_rotation_cycles', to='housing.society')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='parking.parkingrotationpolicy')),
            ],
            options={
                'ordering': ('-cycle_start_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ParkingRotationPolicyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_rotation_policy_audits', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='parking.parkingrotationpolicy')),
            ],
            options={
                'ordering': ('-changed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ParkingRotationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_allocated_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_allocations', to='parking.parkingrotationcycle')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_rotation_queue_entries', to='housing.society')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_rotation_queue_entries', to='housing.unit')),
            ],
            options={
                'ordering': ('queue_position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ParkingRotationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_rotation_applications', to='housing.unit')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_rotation_applications', to='parking.vehicle')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='parking.parkingrotationcycle')),
            ],
            options={
                'ordering': ('applied_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('cycle', 'unit', 'vehicle'), name='uniq_rotation_application_per_cycle_unit_vehicle')],
            },
        ),
        migrations.CreateModel(
            name='ParkingRotationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_method', models.CharField(choices=[('QUEUE', 'Queue'), ('LOTTERY', 'Lottery'), ('MANUAL_OVERRIDE', 'Manual Override')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rotation_allocations', to=settings.AUTH_USER_MODEL)),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_rotation_allocations', to='parking.parkingslot')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_rotation_allocations', to='housing.unit')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_rotation_allocations', to='parking.vehicle')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='parking.parkingrotationcycle')),
            ],
            options={
                'ordering': ('-assigned_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('cycle', 'parking_spot'), name='uniq_rotation_allocation_per_cycle_spot')],
            },
        ),
        migrations.AddConstraint(
            model_name='parkingrotationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('society',), name='uniq_active_rotation_policy_per_society'),
        ),
        migrations.AddConstraint(
            model_name='parkingrotationcycle',
            constraint=models.UniqueConstraint(fields=('society', 'cycle_number'), name='uniq_rotation_cycle_number_per_society'),
        ),
        migrations.AddConstraint(
            model_name='parkingrotationqueue',
            constraint=models.UniqueConstraint(fields=('society', 'unit'), name='uniq_rotation_queue_unit_per_society'),
        ),
        migrations.AddConstraint(
            model_name='parkingrotationqueue',
            constraint=models.UniqueConstraint(fields=('society', 'queue_position'), name='uniq_rotation_queue_position_per_society'),
        ),
    ]
