# Generated by Django 5.2.10 on 2026-05-01 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0025_alter_account_options_alter_account_unique_together_and_more'),
        ('housing', '0008_emailverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(help_text='Unique certificate number', max_length=50, unique=True)),
                ('share_count', models.DecimalField(decimal_places=2, help_text='Number of shares covered by this certificate', max_digits=12)),
                ('issued_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('REPLACED', 'Replaced'), ('ISSUED', 'Issued'), ('TRANSFERRED', 'Transferred'), ('LOST', 'Lost (Replacement Issued)')], default='ACTIVE', max_length=20)),
                ('transferred_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_certificates', to='housing.member')),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_certificates', to='housing.member')),
            ],
            options={
                'verbose_name': 'Share Certificate',
                'verbose_name_plural': 'Share Certificates',
                'ordering': ['-issued_date', 'certificate_no'],
                'indexes': [models.Index(fields=['member', 'status'], name='shares_shar_member__e42cca_idx'), models.Index(fields=['certificate_no'], name='shares_shar_certifi_5ef720_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShareLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_in', models.DecimalField(decimal_places=2, default=0, help_text='Shares coming in', max_digits=12)),
                ('shares_out', models.DecimalField(decimal_places=2, default=0, help_text='Shares going out', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Running balance after this transaction', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('ALLOTMENT', 'Share Allotment'), ('TRANSFER', 'Transfer'), ('TRANSMISSION', 'Transmission'), ('CORRECTION', 'Correction'), ('TRANSFER_IN', 'Transfer In (from another member)'), ('TRANSFER_OUT', 'Transfer Out (to another member)'), ('FORFEITURE', 'Share Forfeiture'), ('BUYBACK', 'Share Buyback by Society'), ('ADJUSTMENT', 'Balance Adjustment (with reason)')], max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='External reference (transfer ID, certificate number, etc.)', max_length=100)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for adjustment/forfeiture/transmission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_transactions', to='housing.member')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_transactions', to='housing.society')),
                ('voucher', models.ForeignKey(blank=True, help_text='Voucher generated for this share transaction (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_transactions', to='accounting.voucher')),
            ],
            options={
                'verbose_name': 'Share Ledger Entry',
                'verbose_name_plural': 'Share Ledger Entries',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['member', 'transaction_date'], name='shares_shar_member__2709bc_idx'), models.Index(fields=['transaction_type', 'transaction_date'], name='shares_shar_transac_2d268a_idx'), models.Index(fields=['society', 'member', 'transaction_date'], name='shares_shar_society_c33da1_idx'), models.Index(fields=['society', 'transaction_date'], name='shares_shar_society_e40d87_idx'), models.Index(fields=['voucher'], name='shares_shar_voucher_b89b27_idx')],
            },
        ),
    ]
