# Generated by Django 5.2.10 on 2026-05-01 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0010_add_share_fields_to_member'),
        ('shares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the event occurred')),
                ('event_type', models.CharField(choices=[('SHARE_ALLOTMENT', 'Share Allotment'), ('SHARE_TRANSFER', 'Share Transfer'), ('SHARE_TRANSMISSION', 'Share Transmission'), ('SHARE_CORRECTION', 'Share Correction'), ('SHARE_FORFEITURE', 'Share Forfeiture'), ('SHARE_BUYBACK', 'Share Buyback'), ('SHARE_ADJUSTMENT', 'Share Adjustment'), ('NOMINEE_ADDED', 'Nominee Added'), ('NOMINEE_UPDATED', 'Nominee Updated'), ('NOMINEE_REMOVED', 'Nominee Removed'), ('SHARE_CERTIFICATE_ISSUED', 'Share Certificate Issued'), ('SHARE_CERTIFICATE_CANCELLED', 'Share Certificate Cancelled'), ('SHARE_CERTIFICATE_REPLACED', 'Share Certificate Replaced'), ('SHARE_CERTIFICATE_TRANSFERRED', 'Share Certificate Transferred'), ('MEMBER_SHARE_BALANCE_CHANGED', 'Member Share Balance Changed')], db_index=True, max_length=50)),
                ('share_count', models.DecimalField(blank=True, decimal_places=2, help_text='Number of shares involved', max_digits=12, null=True)),
                ('share_value', models.DecimalField(blank=True, decimal_places=2, help_text='Value per share (if applicable)', max_digits=15, null=True)),
                ('certificate_number', models.CharField(blank=True, help_text='Certificate number (if applicable)', max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the event')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured context (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_member', models.ForeignKey(blank=True, help_text='Member transferring shares (for transfers)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_logs_as_sender', to='housing.member')),
                ('member', models.ForeignKey(blank=True, help_text='Primary member involved in the event', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_logs', to='housing.member')),
                ('nominee', models.ForeignKey(blank=True, help_text='Nominee involved (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='housing.nominee')),
                ('performed_by', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.PROTECT, related_name='performed_events', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(help_text='Society where the event occurred', on_delete=django.db.models.deletion.PROTECT, related_name='event_logs', to='housing.society')),
                ('to_member', models.ForeignKey(blank=True, help_text='Member receiving shares (for transfers)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_logs_as_receiver', to='housing.member')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-timestamp', '-created_at'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='shares_even_event_t_6da359_idx'), models.Index(fields=['member', 'timestamp'], name='shares_even_member__aa5015_idx'), models.Index(fields=['society', 'timestamp'], name='shares_even_society_82db2d_idx'), models.Index(fields=['performed_by', 'timestamp'], name='shares_even_perform_afd906_idx'), models.Index(fields=['certificate_number'], name='shares_even_certifi_994200_idx')],
            },
        ),
    ]
