# Generated by Django 5.2.10 on 2026-04-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the shortcut (e.g., "Purchase Voucher")', max_length=100, verbose_name='name')),
                ('key_combination', models.CharField(help_text='Key combination like "F9", "Ctrl+Alt+R". Will be normalized to uppercase.', max_length=50, verbose_name='key combination')),
                ('action_type', models.CharField(choices=[('URL', 'URL Redirect'), ('MODAL', 'Open Modal'), ('JS', 'Custom JS Action')], default='URL', max_length=20, verbose_name='action type')),
                ('action_value', models.CharField(help_text='URL → "/voucher/purchase/"\nMODAL → URL to load modal content\nJS → JavaScript function name like "runReconciliation()"', max_length=255, verbose_name='action value')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('PAGE', 'Page Specific')], default='GLOBAL', max_length=20, verbose_name='scope')),
                ('page', models.CharField(blank=True, help_text='Page identifier for page-specific shortcuts (e.g., "voucher_page", "dashboard")', max_length=100, null=True, verbose_name='page')),
                ('role', models.CharField(blank=True, help_text='Optional role restriction (e.g., "ACCOUNTANT", "ADMIN"). Leave empty for all roles.', max_length=50, null=True, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this shortcut is currently active', verbose_name='active')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shortcuts take precedence', verbose_name='priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('normalized_key', models.CharField(db_index=True, editable=False, max_length=50, verbose_name='normalized key')),
            ],
            options={
                'verbose_name': 'keyboard shortcut',
                'verbose_name_plural': 'keyboard shortcuts',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['normalized_key', 'is_active'], name='administrat_normali_227d65_idx'), models.Index(fields=['scope', 'page', 'is_active'], name='administrat_scope_d939e7_idx'), models.Index(fields=['role', 'is_active'], name='administrat_role_13a578_idx')],
            },
        ),
    ]
