"""
Phase 13 — Analytics Snapshot model.

Pre-computed aggregate metrics cached per society per date to avoid
expensive live queries on large GateEvent datasets.  Most analytics
are live queries (see AnalyticsService); snapshots are used for
historical data and long-term trend analysis.
"""

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from societies.models import Society


class AnalyticsSnapshot(models.Model):
    """Pre-computed aggregate metrics for a society on a given date.

    Generated by the ``generate_analytics_snapshot`` management command and
    consumed by historical trend charts to avoid expensive ``GROUP BY``
    queries on large :class:`GateEvent` tables.  Each row caches a JSON blob
    of metrics for a single ``(society, date, snapshot_type)`` tuple.

    Soft-delete follows the established ``is_active`` + ``deleted_at`` pattern
    (matching :class:`ShiftHandover`, :class:`SecurityGuard`, :class:`Person`).
    The conditional unique constraint only enforces uniqueness among active
    snapshots, so re-generation upserts rather than duplicates.
    """

    class SnapshotType(models.TextChoices):
        DAILY = "daily", _("Daily")
        WEEKLY = "weekly", _("Weekly")
        MONTHLY = "monthly", _("Monthly")
        CUSTOM = "custom", _("Custom Range")

    society = models.ForeignKey(
        Society,
        on_delete=models.CASCADE,
        related_name="gateops_analytics_snapshots",
        verbose_name=_("society"),
    )
    # The date this snapshot covers.  For DAILY this is the calendar date.
    # For WEEKLY this is the Monday of the week; for MONTHLY the 1st of the
    # month.  Enforced by ``clean()``.
    date = models.DateField(_("date"), db_index=True)
    snapshot_type = models.CharField(
        _("snapshot type"),
        max_length=10,
        choices=SnapshotType.choices,
        default=SnapshotType.DAILY,
    )
    # Pre-computed metrics stored as JSON so the schema can evolve without
    # migrations.  See "Metrics JSON Schema" in PHASE_13_ANALYTICS.md.
    metrics = models.JSONField(_("metrics"), default=dict)
    generated_at = models.DateTimeField(_("generated at"), auto_now_add=True)

    # --- Soft-delete pattern (inline, no mixin) ---
    is_active = models.BooleanField(_("active"), default=True)
    deleted_at = models.DateTimeField(_("deleted at"), null=True, blank=True)

    class Meta:
        verbose_name = _("Analytics Snapshot")
        verbose_name_plural = _("Analytics Snapshots")
        ordering = ["-date", "-generated_at"]
        indexes = [
            models.Index(
                fields=["society", "-date"], name="analytics_snap_soc_date_idx"
            ),
            models.Index(
                fields=["society", "snapshot_type", "-date"],
                name="anlsnap_soc_type_date_idx",
            ),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=["society", "date", "snapshot_type"],
                condition=Q(is_active=True),
                name="uniq_analytics_snapshot_per_day",
            ),
        ]

    def __str__(self):
        return f"{self.society.name} — {self.snapshot_type} snapshot for {self.date}"

    @property
    def is_deleted(self) -> bool:
        return not self.is_active

    def clean(self):
        super().clean()
        if self.date is None:
            raise ValidationError({"date": _("date is required.")})
        if self.snapshot_type == self.SnapshotType.WEEKLY and self.date.weekday() != 0:
            raise ValidationError(
                {"date": _("Weekly snapshots must have a Monday date.")}
            )
        if self.snapshot_type == self.SnapshotType.MONTHLY and self.date.day != 1:
            raise ValidationError(
                {"date": _("Monthly snapshots must have the 1st of the month.")}
            )

    def delete(self, *args, **kwargs):
        """Soft-delete: set ``is_active=False`` and ``deleted_at=now()``.

        Does not call ``super().delete()`` — the row is retained for audit
        and historical trend queries.  Idempotent: a no-op if already
        soft-deleted, so ``deleted_at`` is not bumped on repeated calls.
        """
        if not self.is_active:
            return
        self.is_active = False
        self.deleted_at = timezone.now()
        self.save(update_fields=["is_active", "deleted_at"])
