from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _


class PeakHourPrediction(models.Model):
    """Predicted visitor counts per ``(society, day_of_week, hour)`` slot.

    Phase 11 — AI Engine. Generated by the batch analysis command and consumed
    by the analytics dashboard (Phase 13) and staffing recommendations. Each row
    predicts the number of visitor entries for a specific hour of a specific
    weekday, with a confidence score based on the volume of historical data.

    Soft-delete follows the established ``is_active`` + ``deleted_at`` pattern.
    The conditional unique constraint on
    ``(society, day_of_week, hour, analysis_date)`` only enforces uniqueness
    among active predictions, so re-running prediction on the same day upserts
    rather than duplicates.
    """

    society = models.ForeignKey(
        "housing.Society",
        on_delete=models.CASCADE,
        related_name="peak_hour_predictions",
        verbose_name=_("society"),
    )
    day_of_week = models.PositiveSmallIntegerField(
        _("day of week"),
        help_text=_("ISO weekday: 0=Monday … 6=Sunday."),
    )
    hour = models.PositiveSmallIntegerField(
        _("hour"),
        help_text=_("Hour of day, 24-hour clock (0–23)."),
    )
    predicted_count = models.PositiveIntegerField(_("predicted count"), default=0)
    confidence_score = models.FloatField(_("confidence score"), default=0.0)
    actual_count = models.PositiveIntegerField(
        _("actual count"), null=True, blank=True
    )
    analysis_date = models.DateField(_("analysis date"))
    is_active = models.BooleanField(_("active"), default=True)
    deleted_at = models.DateTimeField(_("deleted at"), null=True, blank=True)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)

    class Meta:
        verbose_name = _("Peak Hour Prediction")
        verbose_name_plural = _("Peak Hour Predictions")
        ordering = ("day_of_week", "hour")
        constraints = [
            models.UniqueConstraint(
                fields=["society", "day_of_week", "hour", "analysis_date"],
                condition=Q(is_active=True),
                name="unique_active_peak_hour_per_slot",
            ),
        ]
        indexes = [
            models.Index(
                fields=["society", "day_of_week", "hour"], name="peak_soc_dow_hr_idx"
            ),
            models.Index(fields=["society", "analysis_date"], name="peak_soc_date_idx"),
            models.Index(fields=["society", "is_active"], name="peak_soc_active_idx"),
        ]

    def __str__(self):
        days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
        day_label = days[self.day_of_week] if 0 <= self.day_of_week <= 6 else "???"
        return (
            f"{day_label} {self.hour:02d}:00 — predicted {self.predicted_count} "
            f"(confidence {self.confidence_score:.0%})"
        )

    def clean(self):
        super().clean()
        if not (0 <= self.day_of_week <= 6):
            raise ValidationError(
                {"day_of_week": _("day_of_week must be 0–6 (Monday–Sunday).")}
            )
        if not (0 <= self.hour <= 23):
            raise ValidationError({"hour": _("hour must be 0–23.")})
        if not (0.0 <= self.confidence_score <= 1.0):
            raise ValidationError(
                {"confidence_score": _("confidence_score must be between 0.0 and 1.0.")}
            )

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)
