# Generated by Django 5.2.10 on 2026-05-01 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0010_add_share_fields_to_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_value', models.DecimalField(decimal_places=2, default=100.0, help_text='Face value of each share', max_digits=12)),
                ('default_share_count', models.PositiveIntegerField(default=1, help_text='Default number of shares allotted to new members')),
                ('entrance_fee', models.DecimalField(decimal_places=2, default=0, help_text='One-time entrance fee for new members', max_digits=12)),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fee for share transfer', max_digits=12)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=0, help_text='Premium amount (if shares are issued above face value)', max_digits=12)),
                ('allow_multiple_nominees', models.BooleanField(default=False, help_text='Allow members to nominate multiple persons')),
                ('require_approval', models.BooleanField(default=True, help_text='Require admin approval for share-related actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.OneToOneField(help_text='Society this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='share_config', to='housing.society')),
            ],
            options={
                'verbose_name': 'Society Configuration',
                'verbose_name_plural': 'Society Configurations',
                'indexes': [models.Index(fields=['society'], name='societies_s_society_343bf9_idx')],
            },
        ),
    ]
