# Generated by Codex to align the current SocietyConfig model with the database.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("societies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="societyconfig",
            name="auto_generate_vouchers",
            field=models.BooleanField(default=True, help_text="Automatically generate accounting vouchers for share transactions"),
        ),
    ]
