# Generated by Django 5.2.10 on 2026-07-08 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0010_add_share_fields_to_member'),
        ('societies', '0002_add_auto_generate_vouchers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('voucher_post', 'Voucher Post'), ('voucher_reverse', 'Voucher Reverse'), ('ownership_transfer', 'Ownership Transfer'), ('role_change', 'Role Change'), ('membership_deactivate', 'Membership Deactivate'), ('bulk_billing', 'Bulk Billing'), ('year_end_close', 'Year End Close'), ('custom', 'Custom')], max_length=30)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict, help_text='Data needed to execute the action upon approval.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('escalation_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-expiry timestamp.', null=True)),
                ('escalation_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='housing.society')),
            ],
            options={
                'ordering': ('-requested_at',),
                'indexes': [models.Index(fields=['society', 'status'], name='societies_a_society_96b000_idx'), models.Index(fields=['society', 'action', 'status'], name='societies_a_society_6884bc_idx'), models.Index(fields=['requested_by', 'status'], name='societies_a_request_a1b9ab_idx'), models.Index(fields=['status', 'expires_at'], name='societies_a_status_d763f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="Full model label, e.g., 'housing.Member', 'accounting.Voucher'.", max_length=100)),
                ('field_name', models.CharField(help_text="Field path, e.g., 'pan_number', 'salary_amount', 'bank_account'.", max_length=100)),
                ('role', models.CharField(help_text="Role this rule applies to. Use '*' for all roles.", max_length=20)),
                ('visible', models.BooleanField(default=True, help_text='True = field visible to this role; False = field hidden.')),
                ('society', models.ForeignKey(blank=True, help_text='If null, this rule applies globally. If set, society-specific override.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_visibility_rules', to='housing.society')),
            ],
            options={
                'verbose_name': 'Field Visibility Rule',
                'verbose_name_plural': 'Field Visibility Rules',
                'indexes': [models.Index(fields=['model_name', 'field_name'], name='societies_f_model_n_6ca48c_idx'), models.Index(fields=['society', 'model_name'], name='societies_f_society_ae658e_idx')],
                'unique_together': {('society', 'model_name', 'field_name', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Required: reason for impersonation.', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired')], default='active', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Auto-expiry timestamp (default: 1 hour from start).')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('impersonator', models.ForeignKey(help_text='The super-admin who initiated the impersonation.', on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions_started', to=settings.AUTH_USER_MODEL)),
                ('target_society', models.ForeignKey(help_text='The society being impersonated into.', on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions', to='housing.society')),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['impersonator', 'status'], name='societies_i_imperso_51a579_idx'), models.Index(fields=['target_society', 'status'], name='societies_i_target__660499_idx'), models.Index(fields=['status', 'expires_at'], name='societies_i_status_157df8_idx')],
            },
        ),
    ]
