# Generated by Django 5.2.10 on 2026-07-07 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0010_add_share_fields_to_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('post', 'Post'), ('reverse', 'Reverse'), ('cancel', 'Cancel'), ('lock', 'Lock'), ('unlock', 'Unlock'), ('export', 'Export'), ('print', 'Print'), ('restore', 'Restore'), ('archive', 'Archive'), ('login', 'Login'), ('logout', 'Logout'), ('impersonate', 'Impersonate'), ('tenant_switch', 'Tenant Switch'), ('permission_change', 'Permission Change'), ('role_change', 'Role Change')], max_length=30)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('module', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='housing.society')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['society', 'entity_type', 'entity_id'], name='auditlog_ent_idx'), models.Index(fields=['society', 'created_at'], name='auditlog_created_idx'), models.Index(fields=['society', 'action'], name='auditlog_action_idx'), models.Index(fields=['actor', 'created_at'], name='auditlog_actor_idx'), models.Index(fields=['request_id'], name='auditlog_reqid_idx')],
            },
        ),
    ]
