# Generated by Django 5.2.10 on 2026-04-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text='Global role for system-wide permissions and shortcuts', max_length=20, verbose_name='role'),
        ),
    ]
