# Generated by Django 5.2.10 on 2026-04-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
