# Generated by Django 5.2.10 on 2026-05-23 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0026_create_account_mapping'),
        ('housing', '0010_add_share_fields_to_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of uploaded file for duplicate detection', max_length=64)),
                ('raw_file', models.FileField(help_text='Original uploaded statement file, stored permanently', upload_to='bank_statements/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('statement_start_date', models.DateField(blank=True, help_text='Start date of the statement period', null=True)),
                ('statement_end_date', models.DateField(blank=True, help_text='End date of the statement period', null=True)),
                ('import_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_log', models.TextField(blank=True, default='')),
                ('row_count', models.PositiveIntegerField(default=0, help_text='Number of transaction rows imported')),
                ('bank_account', models.ForeignKey(help_text='The bank account this statement belongs to', limit_choices_to={'is_bank': True}, on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_imports', to='accounting.account')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_imports', to='housing.society')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, help_text='Value date if available from bank statement', null=True)),
                ('narration', models.TextField(help_text='Raw bank narration — immutable')),
                ('reference_no', models.CharField(blank=True, db_index=True, default='', help_text='Bank reference / transaction ID', max_length=120)),
                ('cheque_no', models.CharField(blank=True, default='', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dr_cr', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, help_text='Running balance after this transaction', max_digits=12, null=True)),
                ('raw_row_data', models.JSONField(default=dict, help_text='Complete original row data preserved for audit')),
                ('duplicate_hash', models.CharField(blank=True, db_index=True, default='', help_text='Hash of date+amount+narration+reference for internal duplicate detection', max_length=64)),
                ('is_duplicate', models.BooleanField(default=False, help_text='Flagged as duplicate within this import batch')),
                ('bank_statement_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='reconciliation.bankstatementimport')),
            ],
            options={
                'ordering': ('transaction_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BankTransactionNormalized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_narration', models.TextField(blank=True, default='', help_text='Cleaned and normalized narration text')),
                ('extracted_utr', models.CharField(blank=True, db_index=True, default='', help_text='Extracted UTR / transaction reference number', max_length=64)),
                ('extracted_flat_no', models.CharField(blank=True, default='', help_text='Extracted flat/unit number from narration', max_length=20)),
                ('extracted_reference', models.CharField(blank=True, default='', help_text='Extracted reference from narration', max_length=120)),
                ('extracted_amount_words', models.CharField(blank=True, default='', help_text='Extracted amount in words from narration', max_length=255)),
                ('normalized_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='reconciliation.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_amount', models.DecimalField(decimal_places=2, help_text='The amount being matched in this link (for partial/split matches)', max_digits=12)),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact'), ('PARTIAL', 'Partial'), ('SPLIT', 'Split'), ('FORCE', 'Force')], default='EXACT', max_length=20)),
                ('confidence_score', models.IntegerField(default=0, help_text='Match confidence 0-100. Higher values = stronger match.')),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('is_manual', models.BooleanField(default=False, help_text='True if manually matched by a user, False if auto-matched')),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUGGESTED', 'Suggested'), ('MATCHED', 'Matched'), ('PARTIAL', 'Partial'), ('DUPLICATE', 'Duplicate'), ('EXCEPTION', 'Exception'), ('REVERSED', 'Reversed'), ('FORCE_MATCHED', 'Force Matched'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20)),
                ('bank_transaction', models.ForeignKey(help_text='The bank transaction being matched', on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_links', to='reconciliation.banktransaction')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_matches', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_links', to='housing.society')),
                ('voucher_entry', models.ForeignKey(help_text='The accounting ledger entry being reconciled', on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_links', to='accounting.ledgerentry')),
            ],
            options={
                'ordering': ('-matched_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReconciliationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('UNMATCHED', 'Unmatched'), ('REVERSED', 'Reversed'), ('FORCE_MATCHED', 'Force Matched'), ('CONFIRMED', 'Confirmed'), ('DUPLICATE', 'Duplicate Flagged'), ('EXCEPTION', 'Exception Marked'), ('IGNORED', 'Ignored')], max_length=30)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('previous_match_type', models.CharField(blank=True, default='', max_length=20)),
                ('new_match_type', models.CharField(blank=True, default='', max_length=20)),
                ('previous_confidence', models.IntegerField(blank=True, null=True)),
                ('new_confidence', models.IntegerField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict, help_text='Additional context about the action (e.g., reason, old values)')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_history', to=settings.AUTH_USER_MODEL)),
                ('reconciliation_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reconciliation.reconciliationlink')),
            ],
            options={
                'verbose_name_plural': 'Reconciliation Histories',
                'ordering': ('-performed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['society', 'bank_account'], name='reconciliat_society_7d6c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['society', 'import_status'], name='reconciliat_society_906af8_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['society', 'file_hash'], name='reconciliat_society_0b4882_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['society', 'statement_start_date', 'statement_end_date'], name='reconciliat_society_870656_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_statement_import', 'transaction_date'], name='reconciliat_bank_st_1ca353_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['reference_no'], name='reconciliat_referen_1225b3_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['cheque_no'], name='reconciliat_cheque__e32d39_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['duplicate_hash'], name='reconciliat_duplica_d02477_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['amount', 'transaction_date'], name='reconciliat_amount_3180eb_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransactionnormalized',
            index=models.Index(fields=['extracted_utr'], name='reconciliat_extract_3ffe52_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransactionnormalized',
            index=models.Index(fields=['extracted_flat_no'], name='reconciliat_extract_535018_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransactionnormalized',
            index=models.Index(fields=['extracted_reference'], name='reconciliat_extract_87da7a_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationlink',
            index=models.Index(fields=['society', 'status'], name='reconciliat_society_27feaf_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationlink',
            index=models.Index(fields=['society', 'voucher_entry'], name='reconciliat_society_b9f026_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationlink',
            index=models.Index(fields=['society', 'bank_transaction'], name='reconciliat_society_94307d_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationlink',
            index=models.Index(fields=['voucher_entry', 'bank_transaction'], name='reconciliat_voucher_efbd73_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationlink',
            index=models.Index(fields=['status', 'matched_at'], name='reconciliat_status_090379_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationhistory',
            index=models.Index(fields=['reconciliation_link', 'performed_at'], name='reconciliat_reconci_fc131f_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationhistory',
            index=models.Index(fields=['performed_by', 'performed_at'], name='reconciliat_perform_a3ad8c_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationhistory',
            index=models.Index(fields=['action', 'performed_at'], name='reconciliat_action_28ac3b_idx'),
        ),
    ]
