# Generated by Django 5.2.10 on 2026-05-23 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_create_account_mapping'),
        ('housing', '0010_add_share_fields_to_member'),
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationlink',
            name='exception_type',
            field=models.CharField(blank=True, choices=[('BOOK_ONLY', 'Book Only (missing in bank)'), ('BANK_ONLY', 'Bank Only (missing in books)'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('DATE_MISMATCH', 'Date Mismatch'), ('DUPLICATE_BOOK', 'Duplicate Book Entry'), ('DUPLICATE_BANK', 'Duplicate Bank Entry')], default='', help_text='Categorizes the type of exception for reporting and resolution', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reconciliationlink',
            index=models.Index(fields=['society', 'exception_type'], name='reconciliat_society_96fb47_idx'),
        ),
    ]
