# Generated by Django 5.2.10 on 2026-07-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_source_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankparserprofile',
            new_name='reconciliat_society_27ef7e_idx',
            old_name='reconciliat_societ_3d86d1_idx',
        ),
        migrations.RenameIndex(
            model_name='bankparserprofile',
            new_name='reconciliat_society_63cc63_idx',
            old_name='reconciliat_societ_93fa1f_idx',
        ),
    ]
