# Generated by Django 5.2.10 on 2026-06-28 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateops', '0001_initial'),
        ('housing', '0010_add_share_fields_to_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Uppercase alphanumeric code, unique per society among active rules.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower number = higher priority (evaluated first).')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('applies_on', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('both', 'Both')], default='both', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateops_rules_created', to=settings.AUTH_USER_MODEL)),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='gateops.gate')),
                ('material_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='gateops.materialcategory')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateops_rules', to='housing.society')),
                ('vehicle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='gateops.vehiclecategory')),
                ('visitor_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='gateops.visitorcategory')),
            ],
            options={
                'verbose_name': 'Gate Operations Rule',
                'verbose_name_plural': 'Gate Operations Rules',
                'ordering': ('society', 'priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('auto_approve', 'Auto Approve'), ('reject', 'Reject'), ('require_approval', 'Require Approval'), ('require_resident_approval', 'Require Resident Approval'), ('notify_security', 'Notify Security'), ('emergency_override', 'Emergency Override'), ('direct_entry', 'Direct Entry'), ('flag_for_review', 'Flag for Review'), ('send_notification', 'Send Notification'), ('escalate', 'Escalate')], max_length=30)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('execution_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='gateops.rule')),
            ],
            options={
                'verbose_name': 'Rule Action',
                'verbose_name_plural': 'Rule Actions',
                'ordering': ('rule', 'execution_order'),
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('visitor_type', 'Visitor Type'), ('time', 'Time of Day'), ('date', 'Date'), ('tower', 'Tower'), ('wing', 'Wing'), ('flat', 'Flat'), ('resident', 'Resident'), ('vehicle', 'Vehicle'), ('guard', 'Guard'), ('gate', 'Gate'), ('max_visitors', 'Max Visitors Inside'), ('max_stay', 'Maximum Stay Hours'), ('holiday', 'Holiday'), ('blacklist', 'Blacklist Status'), ('contractor_expiry', 'Contractor Expiry'), ('pass_valid', 'Pass Validity'), ('visitor_category', 'Visitor Category'), ('vehicle_category', 'Vehicle Category'), ('is_emergency', 'Is Emergency'), ('is_vip', 'Is VIP')], max_length=30)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('neq', 'Not Equals'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('in', 'In'), ('not_in', 'Not In'), ('contains', 'Contains'), ('regex', 'Regex Match'), ('between', 'Between'), ('is_true', 'Is True'), ('is_false', 'Is False')], max_length=20)),
                ('value', models.JSONField(default=dict)),
                ('logical_connector', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', help_text='Connects this condition to the NEXT condition in sort order.', max_length=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='gateops.rule')),
            ],
            options={
                'verbose_name': 'Rule Condition',
                'verbose_name_plural': 'Rule Conditions',
                'ordering': ('rule', 'sort_order'),
            },
        ),
        migrations.CreateModel(
            name='RuleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('input_context', models.JSONField(default=dict)),
                ('matched_conditions', models.JSONField(blank=True, default=dict)),
                ('action_taken', models.CharField(choices=[('auto_approve', 'Auto Approve'), ('reject', 'Reject'), ('require_approval', 'Require Approval'), ('require_resident_approval', 'Require Resident Approval'), ('notify_security', 'Notify Security'), ('emergency_override', 'Emergency Override'), ('direct_entry', 'Direct Entry'), ('flag_for_review', 'Flag for Review'), ('send_notification', 'Send Notification'), ('escalate', 'Escalate'), ('no_match', 'No Match'), ('error', 'Error')], max_length=30)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateops_rule_evaluations', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='gateops.rule')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateops_rule_evaluations', to='housing.society')),
            ],
            options={
                'verbose_name': 'Rule Evaluation Log',
                'verbose_name_plural': 'Rule Evaluation Logs',
                'ordering': ('-evaluated_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['society', 'is_active'], name='rule_soc_act_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['society', 'priority'], name='rule_soc_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['society', 'applies_on'], name='rule_soc_appl_idx'),
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('society', 'code'), name='uniq_rule_code_per_society'),
        ),
        migrations.AddIndex(
            model_name='ruleaction',
            index=models.Index(fields=['rule', 'execution_order'], name='ruleact_order_idx'),
        ),
        migrations.AddIndex(
            model_name='rulecondition',
            index=models.Index(fields=['rule', 'sort_order'], name='rulecond_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleevaluation',
            index=models.Index(fields=['society', '-evaluated_at'], name='ruleeval_time_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleevaluation',
            index=models.Index(fields=['society', 'rule'], name='ruleeval_rule_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleevaluation',
            index=models.Index(fields=['society', 'action_taken'], name='ruleeval_act_idx'),
        ),
    ]
