# Generated by Django 5.2.10 on 2026-07-05 12:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateops', '0002_rule_ruleaction_rulecondition_ruleevaluation_and_more'),
        ('housing', '0010_add_share_fields_to_member'),
        ('parking', '0008_alter_parkingpermit_permit_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='event UUID')),
                ('event_type', models.CharField(choices=[('invitation', 'Invitation'), ('arrival', 'Arrival'), ('entry', 'Entry'), ('exit', 'Exit'), ('auto_close', 'Auto Close'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('rejected', 'Rejected')], max_length=20, verbose_name='event type')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('arrived', 'Arrived'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('entered', 'Entered'), ('exited', 'Exited'), ('auto_closed', 'Auto Closed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='invited', max_length=20, verbose_name='status')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10, verbose_name='direction')),
                ('purpose', models.TextField(blank=True, verbose_name='purpose')),
                ('expected_arrival_at', models.DateTimeField(blank=True, null=True, verbose_name='expected arrival at')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='arrived at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('entered_at', models.DateTimeField(blank=True, null=True, verbose_name='entered at')),
                ('exited_at', models.DateTimeField(blank=True, null=True, verbose_name='exited at')),
                ('auto_close_at', models.DateTimeField(blank=True, null=True, verbose_name='auto close at')),
                ('photo_url', models.URLField(blank=True, verbose_name='photo URL')),
                ('id_verified', models.BooleanField(default=False, verbose_name='ID verified')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('rule_action', models.CharField(blank=True, max_length=30, verbose_name='rule action')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_events', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gate_events', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='gateops.gate', verbose_name='gate')),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='gateops.securityguard', verbose_name='guard')),
                ('pass_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='gateops.passtype', verbose_name='pass')),
                ('rule_evaluated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_events', to='gateops.ruleevaluation', verbose_name='rule evaluation')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_events', to='housing.society', verbose_name='society')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_events', to='parking.vehicle', verbose_name='vehicle')),
                ('visitor_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='gateops.visitorcategory', verbose_name='visitor category')),
            ],
            options={
                'verbose_name': 'gate event',
                'verbose_name_plural': 'gate events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='ruleevaluation',
            name='gate_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_evaluations', to='gateops.gateevent', verbose_name='gate event'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gateops/persons/', verbose_name='photo')),
                ('id_type', models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('passport', 'Passport'), ('dl', 'Driving License'), ('voter', 'Voter ID'), ('other', 'Other')], max_length=20, null=True, verbose_name='ID type')),
                ('id_number_encrypted', models.TextField(blank=True, verbose_name='ID number (encrypted)')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='blacklisted')),
                ('blacklist_reason', models.TextField(blank=True, verbose_name='blacklist reason')),
                ('blacklist_until', models.DateField(blank=True, null=True, verbose_name='blacklist until')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='housing.society', verbose_name='society')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='gateevent',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_events', to='gateops.person', verbose_name='person'),
        ),
        migrations.CreateModel(
            name='GateEventApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20, verbose_name='decision')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('decision_method', models.CharField(blank=True, choices=[('app', 'Mobile App'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('voice', 'Voice Call'), ('in_person', 'In Person')], max_length=20, verbose_name='decision method')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('timeout_at', models.DateTimeField(blank=True, null=True, verbose_name='timeout at')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL, verbose_name='decided by')),
                ('gate_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='gateops.gateevent', verbose_name='gate event')),
                ('requested_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='requested from')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_event_approvals', to='housing.society', verbose_name='society')),
            ],
            options={
                'verbose_name': 'gate event approval',
                'verbose_name_plural': 'gate event approvals',
                'ordering': ('-requested_at',),
                'indexes': [models.Index(fields=['gate_event'], name='gateappr_evt_idx'), models.Index(fields=['society', 'decision'], name='gateappr_dec_idx')],
            },
        ),
        migrations.CreateModel(
            name='GateEventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, verbose_name='document type')),
                ('file', models.FileField(upload_to='gateops/documents/', verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('gate_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gateops.gateevent', verbose_name='gate event')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.society', verbose_name='society')),
            ],
            options={
                'verbose_name': 'gate event document',
                'verbose_name_plural': 'gate event documents',
                'ordering': ('-uploaded_at',),
                'indexes': [models.Index(fields=['gate_event'], name='gatedoc_evt_idx')],
            },
        ),
        migrations.CreateModel(
            name='GateEventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('arrival', 'Arrival'), ('exit', 'Exit'), ('vehicle', 'Vehicle'), ('material', 'Material'), ('id_document', 'ID Document')], default='arrival', max_length=20, verbose_name='photo type')),
                ('image', models.ImageField(upload_to='gateops/events/', verbose_name='image')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='captured at')),
                ('gate_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gateops.gateevent', verbose_name='gate event')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.society', verbose_name='society')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'gate event photo',
                'verbose_name_plural': 'gate event photos',
                'ordering': ('-captured_at',),
                'indexes': [models.Index(fields=['gate_event'], name='gatephoto_evt_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['society', 'is_blacklisted'], name='person_bl_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['society', 'is_vip'], name='person_vip_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('phone__gt', '')), fields=('society', 'phone'), name='uniq_person_phone_per_society'),
        ),
        migrations.AddIndex(
            model_name='gateevent',
            index=models.Index(fields=['society', 'status'], name='gateevt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='gateevent',
            index=models.Index(fields=['society', 'entered_at'], name='gateevt_entered_idx'),
        ),
        migrations.AddIndex(
            model_name='gateevent',
            index=models.Index(fields=['society', 'created_at'], name='gateevt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='gateevent',
            index=models.Index(fields=['event_uuid'], name='gateevt_uuid_idx'),
        ),
    ]
