# Generated by Django 5.2.10 on 2026-07-06 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateops', '0003_visitor_lifecycle'),
        ('housing', '0010_add_share_fields_to_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code')),
                ('valid_from', models.DateTimeField(verbose_name='valid from')),
                ('valid_until', models.DateTimeField(verbose_name='valid until')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='usage count')),
                ('max_usage', models.PositiveIntegerField(blank=True, help_text='Maximum number of uses. Null means unlimited.', null=True, verbose_name='max usage')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('pass_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passes', to='gateops.passtype', verbose_name='pass type')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passes', to='gateops.person', verbose_name='person')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='housing.society', verbose_name='society')),
            ],
            options={
                'verbose_name': 'Pass',
                'verbose_name_plural': 'Passes',
                'ordering': ('society', '-created_at'),
                'indexes': [models.Index(fields=['society', 'status'], name='pass_soc_status_idx'), models.Index(fields=['society', 'person'], name='pass_soc_person_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('society', 'code'), name='uniq_pass_code_per_society')],
            },
        ),
        # Repoint GateEvent.pass_ref FK from gateops.passtype to gateops.pass
        # (design doc line 1365: "Extends: GateEvent.pass_ref FK"). A pass is
        # now linked directly to the gate event that consumed it, rather than
        # to the pass-type template.
        migrations.AlterField(
            model_name='gateevent',
            name='pass_ref',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='events',
                to='gateops.pass',
                verbose_name='pass',
            ),
        ),
    ]
