# Generated by Django 5.2.10 on 2026-07-06 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateops', '0004_pass_management'),
        ('housing', '0010_add_share_fields_to_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(db_index=True, max_length=30, verbose_name='vehicle number')),
                ('is_watchlisted', models.BooleanField(db_index=True, default=False, verbose_name='watchlisted')),
                ('watchlist_reason', models.TextField(blank=True, verbose_name='watchlist reason')),
                ('is_repeat', models.BooleanField(db_index=True, default=False, verbose_name='repeat visitor')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='first seen at')),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last seen at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_vehicles', to='gateops.person', verbose_name='person')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_vehicles', to='housing.society', verbose_name='society')),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_vehicles', to='gateops.vehiclecategory', verbose_name='vehicle category')),
            ],
            options={
                'verbose_name': 'Gate Vehicle',
                'verbose_name_plural': 'Gate Vehicles',
                'ordering': ('society', '-last_seen_at'),
            },
        ),
        migrations.AddField(
            model_name='gateevent',
            name='gate_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_events', to='gateops.gatevehicle', verbose_name='gate vehicle'),
        ),
        migrations.AddIndex(
            model_name='gatevehicle',
            index=models.Index(fields=['society', 'is_watchlisted'], name='gveh_soc_watchlist_idx'),
        ),
        migrations.AddIndex(
            model_name='gatevehicle',
            index=models.Index(fields=['society', 'vehicle_category'], name='gveh_soc_category_idx'),
        ),
        migrations.AddIndex(
            model_name='gatevehicle',
            index=models.Index(fields=['society', 'person'], name='gveh_soc_person_idx'),
        ),
        migrations.AddConstraint(
            model_name='gatevehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('society', 'vehicle_number'), name='uniq_gate_vehicle_number_per_society'),
        ),
    ]
