# Generated by Django 5.2.10 on 2026-07-06 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateops', '0005_vehicle_module'),
        ('housing', '0010_add_share_fields_to_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantity')),
                ('unit', models.CharField(default='unit', max_length=20, verbose_name='unit')),
                ('owner', models.CharField(blank=True, max_length=200, verbose_name='owner')),
                ('purpose', models.TextField(blank=True, verbose_name='purpose')),
                ('expected_return_at', models.DateTimeField(blank=True, null=True, verbose_name='expected return at')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='returned at')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='gateops/materials/signatures/', verbose_name='signature')),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='in_transit', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('gate_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_movements', to='gateops.gateevent', verbose_name='gate event')),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_movements', to='gateops.materialcategory', verbose_name='material category')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_movements', to='housing.society', verbose_name='society')),
            ],
            options={
                'verbose_name': 'Material Movement',
                'verbose_name_plural': 'Material Movements',
                'ordering': ('society', '-created_at'),
                'indexes': [models.Index(fields=['society', 'status'], name='matmov_soc_status_idx'), models.Index(fields=['society', 'material_category'], name='matmov_soc_cat_idx'), models.Index(fields=['society', 'gate_event'], name='matmov_soc_event_idx'), models.Index(fields=['society', 'expected_return_at'], name='matmov_soc_return_idx')],
            },
        ),
    ]
