from django.urls import path

from gateops import views

app_name = "gateops"

urlpatterns = [
    path("", view=views.gateops_dashboard_view, name="dashboard"),
    path("setup/", view=views.setup_index_view, name="setup-index"),
    path("setup/<slug:slug>/", view=views.setup_section_view, name="setup-section"),
    path("setup/<slug:slug>/create/", view=views.setup_create_view, name="setup-create"),
    path("setup/<slug:slug>/<int:pk>/edit/", view=views.setup_edit_view, name="setup-edit"),
    path("setup/<slug:slug>/<int:pk>/delete/", view=views.setup_delete_view, name="setup-delete"),
    path("setup/<slug:slug>/<int:pk>/move/<str:direction>/", view=views.setup_move_view, name="setup-move"),
    path("rules/", view=views.rule_list_view, name="rule-list"),
    path("rules/create/", view=views.rule_create_view, name="rule-create"),
    path("rules/<int:pk>/", view=views.rule_detail_view, name="rule-detail"),
    path("rules/<int:pk>/edit/", view=views.rule_edit_view, name="rule-edit"),
    path("rules/<int:pk>/toggle/", view=views.rule_toggle_view, name="rule-toggle"),
    path("rules/<int:pk>/conditions/create/", view=views.condition_create_view, name="condition-create"),
    path("rules/<int:pk>/actions/create/", view=views.action_create_view, name="action-create"),
    path("test/", view=views.rule_test_view, name="rule-test"),
    path("logs/", view=views.logs_view, name="logs"),
    path("events/", view=views.gate_event_list_view, name="event-list"),
    path("events/new/", view=views.gate_event_form_view, name="event-create"),
    path("events/<uuid:uuid>/", view=views.gate_event_detail_view, name="event-detail"),
    path("events/<uuid:uuid>/exit/", view=views.gate_event_record_exit_view, name="event-exit"),
    path("events/<uuid:uuid>/approve/", view=views.gate_event_approve_view, name="event-approve"),
    path("events/<uuid:uuid>/reject/", view=views.gate_event_reject_view, name="event-reject"),
    path("currently-inside/", view=views.currently_inside_view, name="currently-inside"),
    # --- Phase 5: Pass Management ---
    path("passes/", view=views.pass_list_view, name="pass-list"),
    path("passes/<int:pk>/", view=views.pass_detail_view, name="pass-detail"),
    path("passes/<int:pk>/revoke/", view=views.pass_revoke_view, name="pass-revoke"),
    path("passes/<int:pk>/suspend/", view=views.pass_suspend_view, name="pass-suspend"),
    path("passes/<int:pk>/reactivate/", view=views.pass_reactivate_view, name="pass-reactivate"),
    path("passes/<int:pk>/validate/", view=views.pass_validate_view, name="pass-validate"),
    path("passes/issue/", view=views.pass_issue_view, name="pass-issue"),
    # --- Phase 6: Vehicle Module ---
    path("vehicles/", view=views.vehicle_list_view, name="vehicle-list"),
    path("vehicles/register/", view=views.vehicle_register_view, name="vehicle-register"),
    path("vehicles/search/", view=views.vehicle_search_view, name="vehicle-search"),
    path("vehicles/anpr-lookup/", view=views.vehicle_anpr_lookup_view, name="vehicle-anpr-lookup"),
    path("vehicles/<int:pk>/", view=views.vehicle_detail_view, name="vehicle-detail"),
    path("vehicles/<int:pk>/watchlist/", view=views.vehicle_watchlist_view, name="vehicle-watchlist"),
    path("vehicles/<int:pk>/unwatchlist/", view=views.vehicle_unwatchlist_view, name="vehicle-unwatchlist"),
    # --- Phase 7: Material Movement ---
    path("materials/", view=views.material_list_view, name="material-list"),
    path("materials/record/", view=views.material_record_view, name="material-record"),
    path("materials/pending/", view=views.material_pending_view, name="material-pending"),
    path("materials/overdue/", view=views.material_overdue_view, name="material-overdue"),
    path("materials/<int:pk>/", view=views.material_detail_view, name="material-detail"),
    path("materials/<int:pk>/return/", view=views.material_return_view, name="material-return"),
    path("materials/<int:pk>/cancel/", view=views.material_cancel_view, name="material-cancel"),
    path("materials/<int:pk>/gate-pass/", view=views.material_gate_pass_view, name="material-gate-pass"),
    # --- Phase 8: Parcel Management ---
    path("parcels/", view=views.parcel_list_view, name="parcel-list"),
    path("parcels/receive/", view=views.parcel_receive_view, name="parcel-receive"),
    path("parcels/pending/", view=views.parcel_pending_view, name="parcel-pending"),
    path("parcels/overdue/", view=views.parcel_overdue_view, name="parcel-overdue"),
    path("parcels/<int:pk>/", view=views.parcel_detail_view, name="parcel-detail"),
    path("parcels/<int:pk>/collect/", view=views.parcel_collect_view, name="parcel-collect"),
    path("parcels/<int:pk>/return/", view=views.parcel_return_view, name="parcel-return"),
    path("parcels/<int:pk>/mark-lost/", view=views.parcel_mark_lost_view, name="parcel-mark-lost"),
    # --- Phase 9: Contractor Management ---
    path("contractors/", views.contractor_list, name="contractor-list"),
    path("contractors/<int:pk>/", views.contractor_detail, name="contractor-detail"),
    path("contractors/create/", views.contractor_create, name="contractor-create"),
    path("contractors/<int:pk>/edit/", views.contractor_edit, name="contractor-edit"),
    path("contractors/<int:pk>/deactivate/", views.contractor_deactivate, name="contractor-deactivate"),
    path("contracts/", views.contract_list, name="contract-list"),
    path("contracts/<int:pk>/", views.contract_detail, name="contract-detail"),
    path("contracts/create/", views.contract_create, name="contract-create"),
    path("contracts/<int:pk>/edit/", views.contract_edit, name="contract-edit"),
    path("contracts/<int:pk>/deactivate/", views.contract_deactivate, name="contract-deactivate"),
    path("workers/", views.worker_list, name="worker-list"),
    path("workers/<int:pk>/", views.worker_detail, name="worker-detail"),
    path("workers/register/", views.worker_register, name="worker-register"),
    path("workers/<int:pk>/edit/", views.worker_edit, name="worker-edit"),
    path("workers/<int:pk>/deactivate/", views.worker_deactivate, name="worker-deactivate"),
    path("work-permits/", views.work_permit_list, name="work-permit-list"),
    path("work-permits/<int:pk>/", views.work_permit_detail, name="work-permit-detail"),
    path("work-permits/issue/", views.work_permit_issue, name="work-permit-issue"),
    path("work-permits/<int:pk>/edit/", views.work_permit_edit, name="work-permit-edit"),
    path("work-permits/<int:pk>/revoke/", views.work_permit_revoke, name="work-permit-revoke"),
    path("contractor-dashboard/", views.contractor_dashboard, name="contractor-dashboard"),
    # --- Phase 12: Exit Management ---
    path("exits/quick/", view=views.quick_exit_view, name="quick-exit"),
    path("exits/qr/", view=views.qr_exit_view, name="qr-exit"),
    path("exits/qr/scan/", view=views.qr_exit_scan_view, name="qr-exit-scan"),
    # Shift handover
    path("handovers/", view=views.handover_list_view, name="handover-list"),
    path("handovers/create/", view=views.handover_create_view, name="handover-create"),
    path("handovers/<uuid:uuid>/", view=views.handover_detail_view, name="handover-detail"),
    path("handovers/<uuid:uuid>/acknowledge/", view=views.handover_acknowledge_view, name="handover-acknowledge"),
    path("handovers/<uuid:uuid>/dispute/", view=views.handover_dispute_view, name="handover-dispute"),
    # --- Phase 13: Analytics ---
    path("analytics/", view=views.analytics_dashboard_view, name="analytics-dashboard"),
    path("analytics/live-visitors/", view=views.analytics_live_visitors_view, name="analytics-live-visitors"),
    path("analytics/peak-hours/", view=views.analytics_peak_hours_view, name="analytics-peak-hours"),
    path("analytics/guard-performance/", view=views.analytics_guard_performance_view, name="analytics-guard-performance"),
    path("analytics/custom-report/", view=views.analytics_custom_report_view, name="analytics-custom-report"),
    path("analytics/rule-violations/", view=views.analytics_rule_violations_view, name="analytics-rule-violations"),
    path("analytics/export/", view=views.analytics_export_view, name="analytics-export"),
]
