# Generated by Django 5.2.10 on 2026-01-26 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('housing', '0003_unitoccupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='society',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='housing.society'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialyear',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='housing.society'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='housing.society'),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accountcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='financialyear',
            unique_together={('society', 'start_date', 'end_date')},
        ),
    ]
