# Generated by Django 5.2.10 on 2026-01-26 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_society_financialyear_society_and_more'),
        ('housing', '0003_unitoccupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accountcategory'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='housing.society'),
        ),
    ]
