# Generated by Django 5.2.10 on 2026-01-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_category_alter_voucher_society'),
        ('housing', '0003_unitoccupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='housing.unit'),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='society',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='housing.society'),
            preserve_default=False,
        ),
    ]
