# Generated by Django 5.2.10 on 2026-01-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_ledgerentry_unit_alter_financialyear_society'),
        ('housing', '0003_unitoccupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='VoucherSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=20)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_sequences', to='housing.society')),
            ],
            options={
                'unique_together': {('society', 'voucher_type')},
            },
        ),
    ]
