# Generated by Django 5.2.10 on 2026-01-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_voucher_voucher_number_vouchersequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('year', 'month'),
                'unique_together': {('year', 'month')},
            },
        ),
    ]
