# Generated by Django 5.2.10 on 2026-02-17 06:14

import re
from django.db import migrations, models


def normalize_financial_year_names(apps, schema_editor):
    FinancialYear = apps.get_model("accounting", "FinancialYear")
    pattern = re.compile(r"^(FY \d{4}-\d{2}) \(\d+\)$")

    for fy in FinancialYear.objects.all():
        match = pattern.match(fy.name)
        if not match:
            continue
        fy.name = match.group(1)
        fy.save(update_fields=["name"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_account_system_protected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcategory',
            options={'ordering': ('society', 'account_type', 'name')},
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.RunPython(normalize_financial_year_names, noop_reverse),
    ]
