# Generated by Django 5.2.10 on 2026-02-17 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_accountcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by_voucher', to='accounting.voucher'),
        ),
    ]
