# Generated by Django 5.2.10 on 2026-02-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_voucher_reversal_of'),
        ('housing', '0003_unitoccupancy'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(condition=models.Q(('voucher_number__isnull', False)), fields=('society', 'voucher_type', 'voucher_number'), name='uniq_voucher_number_per_society_type'),
        ),
    ]
