# Generated by Django 5.2.10 on 2026-02-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_voucher_uniq_voucher_number_per_society_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('CARD', 'Card'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reference_number',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
