# Generated by Django 5.2.10 on 2026-02-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_voucher_payment_mode_voucher_reference_number'),
        ('housing', '0003_unitoccupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'voucher'], name='accounting__account_9173f0_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['voucher', 'id'], name='accounting__voucher_28b8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['society', 'voucher_date'], name='accounting__society_28879b_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['society', 'posted_at', 'voucher_date'], name='accounting__society_1db70b_idx'),
        ),
    ]
