# Generated by Django 5.2.10 on 2026-02-17 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_voucher_voucher_date_and_more'),
        ('housing', '0003_unitoccupancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CLOSED', 'Closed'), ('OPENED', 'Opened')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-performed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='YearEndCloseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-performed_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='periodstatuslog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_status_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodstatuslog',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='accounting.accountingperiod'),
        ),
        migrations.AddField(
            model_name='yearendcloselog',
            name='opening_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carry_forward_logs', to='accounting.voucher'),
        ),
        migrations.AddField(
            model_name='yearendcloselog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_end_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yearendcloselog',
            name='source_financial_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='year_end_close_log', to='accounting.financialyear'),
        ),
        migrations.AddField(
            model_name='yearendcloselog',
            name='target_financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carry_forward_sources', to='accounting.financialyear'),
        ),
    ]
