# Generated by Django 5.2.10 on 2026-02-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_periodstatuslog_yearendcloselog_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE accounting_accountingperiod "
                "DROP CONSTRAINT IF EXISTS uniq_single_open_period_per_year;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
