# Generated by Django 5.2.10 on 2026-02-17

from django.db import migrations


def drop_single_open_period_constraint(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        "ALTER TABLE accounting_accountingperiod "
        "DROP CONSTRAINT IF EXISTS uniq_single_open_period_per_year;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_periodstatuslog_yearendcloselog_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=drop_single_open_period_constraint,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
