# Generated by Django 5.2.10 on 2026-04-08 11:01

from django.db import migrations, models


def mark_default_clearing_accounts(apps, schema_editor):
    Account = apps.get_model("accounting", "Account")
    account_names = [
        "Bank Clearing Account",
        "Suspense Account",
        "Fund Transfer Account",
    ]
    Account.objects.filter(name__in=account_names).update(is_clearing=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_account_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_clearing',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_default_clearing_accounts, migrations.RunPython.noop),
    ]
