# Generated by Django 5.2.10 on 2026-04-14 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_account_is_clearing'),
        ('housing', '0008_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('GENERAL', 'General'), ('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment'), ('ADJUSTMENT', 'Adjustment'), ('OPENING', 'Opening Balance'), ('JOURNAL', 'Journal'), ('BILL', 'Bill')], help_text='Voucher type this template is intended for.', max_length=20)),
                ('name', models.CharField(blank=True, help_text="Human‑readable name for the template (e.g., 'Monthly Maintenance Receipt').", max_length=100)),
                ('narration', models.TextField(blank=True, help_text='Default narration text for vouchers created from this template.')),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('CARD', 'Card'), ('OTHER', 'Other')], help_text='Default payment mode (if applicable).', max_length=20)),
                ('reference_number_pattern', models.CharField(blank=True, help_text="Optional pattern for generating reference numbers (e.g., 'CHQ‑{seq}').", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(help_text='Society that owns this template.', on_delete=django.db.models.deletion.CASCADE, related_name='voucher_templates', to='housing.society')),
            ],
            options={
                'verbose_name': 'Voucher Template',
                'verbose_name_plural': 'Voucher Templates',
                'ordering': ('society', 'voucher_type'),
                'unique_together': {('society', 'voucher_type')},
            },
        ),
        migrations.CreateModel(
            name='VoucherTemplateRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], help_text='Whether this row is a debit or credit entry.', max_length=10)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Suggested amount (leave empty for zero).', max_digits=12, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order of rows within the template (lower numbers appear first).')),
                ('account', models.ForeignKey(help_text='Ledger account to pre‑fill.', on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('template', models.ForeignKey(help_text='The template this row belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='accounting.vouchertemplate')),
                ('unit', models.ForeignKey(blank=True, help_text='Optional unit to link (must belong to the same society).', null=True, on_delete=django.db.models.deletion.PROTECT, to='housing.unit')),
            ],
            options={
                'verbose_name': 'Voucher Template Row',
                'verbose_name_plural': 'Voucher Template Rows',
                'ordering': ('template', 'order', 'id'),
            },
        ),
    ]
