# Generated by Codex on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0023_vouchertemplate_vouchertemplaterow"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vouchertemplate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="vouchertemplate",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Pinned templates are shown before other templates.",
            ),
        ),
        migrations.AddField(
            model_name="vouchertemplate",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this template was most recently used from voucher entry.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vouchertemplate",
            name="sort_order",
            field=models.IntegerField(
                default=0,
                help_text="Manual display order among templates with similar priority.",
            ),
        ),
        migrations.AddField(
            model_name="vouchertemplate",
            name="usage_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this template has been used from voucher entry.",
            ),
        ),
        migrations.AlterModelOptions(
            name="vouchertemplate",
            options={
                "ordering": (
                    "society",
                    "-is_pinned",
                    "-usage_count",
                    "sort_order",
                    "voucher_type",
                    "name",
                    "id",
                ),
                "verbose_name": "Voucher Template",
                "verbose_name_plural": "Voucher Templates",
            },
        ),
    ]
