# Generated by Django 5.2.10 on 2026-04-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_vouchertemplate_quick_action_fields'),
        ('housing', '0008_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('society', 'code')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['society', 'code'], name='accounting__society_9a99cf_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['society', 'account_type'], name='accounting__society_8cdc77_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parent'], name='accounting__parent__da6035_idx'),
        ),
    ]
