# Generated by Django 5.2.10 on 2026-05-01 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_account_options_alter_account_unique_together_and_more'),
        ('housing', '0010_add_share_fields_to_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.ForeignKey(help_text='Bank account (asset) for primary transactions', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('entrance_fee_account', models.ForeignKey(help_text='Income account for entrance fees', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('premium_account', models.ForeignKey(help_text='Equity account for share premium', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('share_capital_account', models.ForeignKey(help_text='Equity account for share capital', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('society', models.OneToOneField(help_text='Society this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='account_mapping', to='housing.society')),
                ('transfer_fee_account', models.ForeignKey(help_text='Income account for share transfer fees', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Account Mapping',
                'verbose_name_plural': 'Account Mappings',
                'indexes': [models.Index(fields=['society'], name='accounting__society_c7af6c_idx')],
            },
        ),
    ]
