# Generated by Django 5.2.10 on 2026-06-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0010_add_share_fields_to_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmailLog',
            fields=[
            ],
            options={
                'verbose_name': 'Email log',
                'verbose_name_plural': 'Email logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('housing.emaillog',),
        ),
        migrations.CreateModel(
            name='AdminEmailQueue',
            fields=[
            ],
            options={
                'verbose_name': 'Email queue',
                'verbose_name_plural': 'Email queue',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('housing.emailqueue',),
        ),
        migrations.CreateModel(
            name='AdminEmailTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('housing.emailtemplate',),
        ),
        migrations.CreateModel(
            name='AdminGlobalEmailSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Global email settings',
                'verbose_name_plural': 'Global email settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('housing.globalemailsettings',),
        ),
        migrations.CreateModel(
            name='AdminSocietyEmailSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Society email settings',
                'verbose_name_plural': 'Society email settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('housing.societyemailsettings',),
        ),
    ]
