# Generated by Django 5.2.10 on 2026-01-23 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(choices=[('BUILDING', 'Building'), ('WING', 'Wing'), ('BLOCK', 'Block'), ('TOWER', 'Tower'), ('FLOOR', 'Floor')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='housing.structure')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='housing.society')),
            ],
            options={
                'ordering': ('display_order', 'id'),
                'unique_together': {('society', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('FLAT', 'Flat'), ('SHOP', 'Shop'), ('OFFICE', 'Office'), ('OTHER', 'Other')], max_length=20)),
                ('identifier', models.CharField(help_text='Flat number / Shop number / Unit code', max_length=50)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='housing.structure')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('structure', 'identifier')},
            },
        ),
    ]
