# Generated by Django 5.2.10 on 2026-02-17 19:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_drop_single_open_period_constraint_if_exists'),
        ('housing', '0003_unitoccupancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.PositiveIntegerField()),
                ('bill_period_start', models.DateField()),
                ('bill_period_end', models.DateField()),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting.account')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='housing.society')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='housing.unit')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting.voucher')),
            ],
            options={
                'ordering': ('-bill_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChargeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('due_days', models.PositiveIntegerField(default=15)),
                ('late_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('income_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_templates_as_income', to='accounting.account')),
                ('receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_templates_as_receivable', to='accounting.account')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_templates', to='housing.society')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('society', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='housing.bill')),
                ('income_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='accounting.account')),
                ('charge_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='housing.chargetemplate')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('TENANT', 'Tenant'), ('NOMINEE', 'Nominee')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receivable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounting.account')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='housing.society')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='housing.unit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='society_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('full_name', 'id'),
                'unique_together': {('society', 'unit', 'full_name', 'role')},
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='housing.member'),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('CARD', 'Card'), ('OTHER', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('VOID', 'Void')], default='POSTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposited_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_as_deposit', to='accounting.account')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='housing.member')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='housing.society')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='housing.unit')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='accounting.voucher')),
            ],
            options={
                'ordering': ('-receipt_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='housing.bill')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='housing.paymentreceipt')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('message', models.TextField()),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='housing.bill')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='housing.member')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='housing.society')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('society', 'bill_number'), ('society', 'member', 'bill_period_start', 'bill_period_end')},
        ),
    ]
