# Generated by Django 5.2.10 on 2026-02-24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0004_bill_chargetemplate_billline_member_bill_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="chargeable_area_sqft",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Authoritative area used for billing calculations.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.RenameField(
            model_name="chargetemplate",
            old_name="amount",
            new_name="rate",
        ),
        migrations.AddField(
            model_name="chargetemplate",
            name="charge_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Fixed Amount"),
                    ("PER_SQFT", "Per Square Foot"),
                    ("PER_PERSON", "Per Person"),
                    ("CUSTOM_FORMULA", "Custom Formula"),
                ],
                default="FIXED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chargetemplate",
            name="effective_from",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="chargetemplate",
            name="effective_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chargetemplate",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="next_versions",
                to="housing.chargetemplate",
            ),
        ),
        migrations.AddField(
            model_name="chargetemplate",
            name="version_no",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="chargetemplate",
            name="rate",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterModelOptions(
            name="chargetemplate",
            options={"ordering": ("name", "-effective_from", "-version_no")},
        ),
        migrations.AlterUniqueTogether(
            name="chargetemplate",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="chargetemplate",
            constraint=models.UniqueConstraint(
                fields=("society", "name", "version_no"),
                name="uniq_charge_template_name_version",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="calculation_basis",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="billline",
            name="charge_type_snapshot",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="billline",
            name="late_fee_percent_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="quantity_snapshot",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1.0000"),
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="rate_snapshot",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="template_version_snapshot",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
