# Generated by Django 5.2.10 on 2026-03-15 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0005_charge_template_versioning_and_billline_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("template_name", models.CharField(max_length=120, unique=True)),
                ("subject_template", models.TextField()),
                ("body_template", models.TextField()),
                ("variables", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("template_name",),
            },
        ),
        migrations.CreateModel(
            name="GlobalEmailSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_type", models.CharField(choices=[("SMTP", "SMTP"), ("SES", "SES"), ("SENDGRID", "SendGrid"), ("MAILGUN", "Mailgun")], default="SMTP", max_length=20)),
                ("smtp_host", models.CharField(max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("smtp_username", models.CharField(blank=True, max_length=255)),
                ("smtp_password_encrypted", models.TextField(blank=True)),
                ("use_tls", models.BooleanField(default=True)),
                ("use_ssl", models.BooleanField(default=False)),
                ("default_from_email", models.CharField(max_length=255)),
                ("default_reply_to", models.EmailField(blank=True, max_length=254)),
                ("daily_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SocietyEmailSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_type", models.CharField(choices=[("SMTP", "SMTP"), ("SES", "SES"), ("SENDGRID", "SendGrid"), ("MAILGUN", "Mailgun")], default="SMTP", max_length=20)),
                ("smtp_host", models.CharField(max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("smtp_username", models.CharField(blank=True, max_length=255)),
                ("smtp_password_encrypted", models.TextField(blank=True)),
                ("use_tls", models.BooleanField(default=True)),
                ("use_ssl", models.BooleanField(default=False)),
                ("default_from_email", models.CharField(max_length=255)),
                ("default_reply_to", models.EmailField(blank=True, max_length=254)),
                ("daily_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("society", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="email_settings", to="housing.society")),
            ],
            options={
                "ordering": ("society__name",),
            },
        ),
        migrations.CreateModel(
            name="EmailQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("body_html", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("email_type", models.CharField(choices=[("AUTHENTICATION", "Authentication"), ("BILLING", "Billing"), ("RECEIPT", "Receipt"), ("NOTICE", "Notice"), ("OTHER", "Other")], default="OTHER", max_length=32)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("PROCESSING", "Processing"), ("SENT", "Sent"), ("FAILED", "Failed"), ("RETRY", "Retry")], default="PENDING", max_length=20)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("scheduled_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("smtp_used", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("from_email", models.CharField(blank=True, max_length=255)),
                ("reply_to_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("society", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="queued_emails", to="housing.society")),
                ("template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="queued_emails", to="housing.emailtemplate")),
            ],
            options={
                "ordering": ("scheduled_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_no", models.PositiveIntegerField()),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("response", models.TextField(blank=True)),
                ("status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("email_queue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="housing.emailqueue")),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="globalemailsettings",
            constraint=models.UniqueConstraint(condition=models.Q(("active", True)), fields=("active",), name="uniq_active_global_email_settings"),
        ),
    ]
