# Generated by Django 5.2.10 on 2026-05-01 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_emailverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(help_text='Relationship to member (e.g., Spouse, Child, Parent)', max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of shares nominated (0-100)', max_digits=5)),
                ('priority_order', models.PositiveIntegerField(default=1, help_text='Priority order for multiple nominees (1 = highest)')),
                ('is_active', models.BooleanField(default=True, help_text="Set to False when nominee is replaced (don't delete)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Timestamp when nominee was replaced/deactivated', null=True)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_nominees', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='housing.member')),
            ],
            options={
                'ordering': ['priority_order', 'created_at'],
                'indexes': [models.Index(fields=['member', 'is_active'], name='housing_nom_member__6111d7_idx'), models.Index(fields=['is_active', 'deactivated_at'], name='housing_nom_is_acti_4acf27_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='nominee_percentage_range'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('member', 'priority_order'), name='unique_active_priority_per_member')],
            },
        ),
    ]
