# Generated by Django 5.2.10 on 2026-05-01 11:37

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_account_options_alter_account_unique_together_and_more'),
        ('housing', '0009_nominee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='member',
            name='share_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['share_balance'], name='housing_mem_share_b_24516b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['join_date'], name='housing_mem_join_da_eb634f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='housing_mem_status_aafa19_idx'),
        ),
    ]
